namespace MLS.Trader.Persistence;

/// <summary>EF Core entity mapped to the <c>trader_orders</c> table.</summary>
public sealed class TradeEntity
{
    /// <summary>Primary key (auto-increment).</summary>
    public long Id { get; set; }

    /// <summary>UUID generated by the Trader at order creation time.</summary>
    public string ClientOrderId { get; set; } = string.Empty;

    /// <summary>Normalised trading symbol, e.g. <c>BTC-USDT</c>.</summary>
    public string Symbol { get; set; } = string.Empty;

    /// <summary>Signal direction: <c>Buy</c>, <c>Sell</c>, or <c>Hold</c>.</summary>
    public string Direction { get; set; } = string.Empty;

    /// <summary>Order size in base asset units.</summary>
    public decimal Quantity { get; set; }

    /// <summary>Entry price at signal time.</summary>
    public decimal EntryPrice { get; set; }

    /// <summary>Computed stop-loss price level.</summary>
    public decimal StopLossPrice { get; set; }

    /// <summary>Computed take-profit price level.</summary>
    public decimal TakeProfitPrice { get; set; }

    /// <summary>Order lifecycle state string (matches <see cref="MLS.Trader.Models.TraderOrderState"/>).</summary>
    public string State { get; set; } = string.Empty;

    /// <summary>Whether this order was simulated in paper-trading mode.</summary>
    public bool PaperTrading { get; set; }

    /// <summary>UTC timestamp when the order was created.</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>UTC timestamp of the most recent state change.</summary>
    public DateTimeOffset UpdatedAt { get; set; }
}
