namespace MLS.Broker.Models;

/// <summary>
/// Request to place a new order on a broker venue.
/// </summary>
/// <param name="Symbol">Normalised trading symbol, e.g. <c>BTC-USDT</c>.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="Type">Order type (Market, Limit, StopMarket, StopLimit).</param>
/// <param name="Quantity">Order size in base asset units.</param>
/// <param name="LimitPrice">Required for Limit and StopLimit orders; <see langword="null"/> for Market/StopMarket.</param>
/// <param name="StopPrice">Required for StopMarket and StopLimit orders; <see langword="null"/> otherwise.</param>
/// <param name="ClientOrderId">UUID generated by the caller — used as idempotency key.</param>
/// <param name="RequestingModuleId">Module ID of the caller (Trader or DeFi).</param>
public sealed record PlaceOrderRequest(
    string Symbol,
    OrderSide Side,
    OrderType Type,
    decimal Quantity,
    decimal? LimitPrice,
    decimal? StopPrice,
    string ClientOrderId,
    string RequestingModuleId);

/// <summary>
/// Request to cancel an open order.
/// </summary>
/// <param name="ClientOrderId">The idempotency key of the order to cancel.</param>
/// <param name="RequestingModuleId">Module ID of the caller.</param>
public sealed record CancelOrderRequest(
    string ClientOrderId,
    string RequestingModuleId);

/// <summary>
/// Result of a place or cancel order call.
/// </summary>
/// <param name="ClientOrderId">Caller-generated idempotency key.</param>
/// <param name="VenueOrderId">Exchange-assigned order ID; <see langword="null"/> when rejected.</param>
/// <param name="State">Current order lifecycle state.</param>
/// <param name="FilledQuantity">How much of the order has been executed so far.</param>
/// <param name="AveragePrice">Volume-weighted average fill price; <see langword="null"/> when unfilled.</param>
/// <param name="Venue">Venue identifier (e.g. <c>hyperliquid</c>).</param>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="CreatedAt">UTC timestamp when the order was first submitted.</param>
/// <param name="UpdatedAt">UTC timestamp of the most recent state change.</param>
public sealed record OrderResult(
    string ClientOrderId,
    string? VenueOrderId,
    OrderState State,
    decimal FilledQuantity,
    decimal? AveragePrice,
    string Venue,
    string Symbol,
    OrderSide Side,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>
/// A single fill (partial or complete) emitted by a venue for an open order.
/// </summary>
/// <param name="ClientOrderId">Caller-generated idempotency key of the filled order.</param>
/// <param name="VenueOrderId">Exchange-assigned order ID.</param>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="FillQuantity">Quantity filled in this event.</param>
/// <param name="FillPrice">Price at which the fill occurred.</param>
/// <param name="TotalFilledQuantity">Cumulative filled quantity including this fill.</param>
/// <param name="RemainingQuantity">Unfilled quantity remaining after this fill.</param>
/// <param name="Venue">Venue identifier.</param>
/// <param name="FilledAt">UTC timestamp of the fill.</param>
public sealed record FillNotification(
    string ClientOrderId,
    string VenueOrderId,
    string Symbol,
    OrderSide Side,
    decimal FillQuantity,
    decimal FillPrice,
    decimal TotalFilledQuantity,
    decimal RemainingQuantity,
    string Venue,
    DateTimeOffset FilledAt);

/// <summary>
/// Current open position for a single symbol on a venue.
/// </summary>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Long or Short expressed as Buy/Sell.</param>
/// <param name="Quantity">Size of the open position in base asset.</param>
/// <param name="AverageEntryPrice">Volume-weighted average entry price.</param>
/// <param name="UnrealisedPnl">Mark-to-market PnL in quote currency.</param>
/// <param name="Venue">Venue identifier.</param>
/// <param name="Timestamp">UTC timestamp of this snapshot.</param>
public sealed record PositionSnapshot(
    string Symbol,
    OrderSide Side,
    decimal Quantity,
    decimal AverageEntryPrice,
    decimal UnrealisedPnl,
    string Venue,
    DateTimeOffset Timestamp);

/// <summary>A real-time order book depth update.</summary>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Bids">Best bid levels as (price, size) pairs.</param>
/// <param name="Asks">Best ask levels as (price, size) pairs.</param>
/// <param name="Timestamp">Exchange timestamp.</param>
public sealed record OrderBookUpdate(
    string Symbol,
    IReadOnlyList<(decimal Price, decimal Size)> Bids,
    IReadOnlyList<(decimal Price, decimal Size)> Asks,
    DateTimeOffset Timestamp);

/// <summary>Order side enumeration.</summary>
public enum OrderSide
{
    /// <summary>Buy (long) side.</summary>
    Buy,
    /// <summary>Sell (short) side.</summary>
    Sell,
}

/// <summary>Order type enumeration.</summary>
public enum OrderType
{
    /// <summary>Execute immediately at best available price.</summary>
    Market,
    /// <summary>Execute at the specified limit price or better.</summary>
    Limit,
    /// <summary>Trigger a market order when the stop price is reached.</summary>
    StopMarket,
    /// <summary>Trigger a limit order when the stop price is reached.</summary>
    StopLimit,
}

/// <summary>Order lifecycle state enumeration.</summary>
public enum OrderState
{
    /// <summary>Order submitted but not yet acknowledged by the venue.</summary>
    Pending,
    /// <summary>Order accepted and resting in the order book.</summary>
    Open,
    /// <summary>Order has been partially executed; remainder resting.</summary>
    PartiallyFilled,
    /// <summary>Order fully executed.</summary>
    Filled,
    /// <summary>Order cancelled by the requester or the venue.</summary>
    Cancelled,
    /// <summary>Order rejected by the venue.</summary>
    Rejected,
}
