namespace MLS.DeFi.Models;

// ── Order placement ───────────────────────────────────────────────────────────

/// <summary>
/// Request to place a new order on a DeFi venue.
/// </summary>
/// <param name="Symbol">Normalised trading symbol, e.g. <c>BTC-USDT</c>.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="Type">Order type.</param>
/// <param name="Quantity">Order size in base asset units.</param>
/// <param name="LimitPrice">Required for Limit/StopLimit orders; <see langword="null"/> otherwise.</param>
/// <param name="StopPrice">Required for StopMarket/StopLimit orders; <see langword="null"/> otherwise.</param>
/// <param name="ClientOrderId">UUID generated by the caller — used as idempotency key.</param>
/// <param name="RequestingModuleId">Module ID of the caller.</param>
public sealed record DeFiOrderRequest(
    string Symbol,
    DeFiOrderSide Side,
    DeFiOrderType Type,
    decimal Quantity,
    decimal? LimitPrice,
    decimal? StopPrice,
    string ClientOrderId,
    string RequestingModuleId);

/// <summary>
/// Result of a place or cancel order call.
/// </summary>
/// <param name="ClientOrderId">Caller-generated idempotency key.</param>
/// <param name="VenueOrderId">Exchange-assigned order ID; <see langword="null"/> when rejected.</param>
/// <param name="State">Current order lifecycle state.</param>
/// <param name="FilledQuantity">How much of the order has been executed.</param>
/// <param name="AveragePrice">Volume-weighted average fill price; <see langword="null"/> when unfilled.</param>
/// <param name="Venue">Venue identifier (e.g. <c>hyperliquid</c>).</param>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="CreatedAt">UTC timestamp when the order was first submitted.</param>
/// <param name="UpdatedAt">UTC timestamp of the most recent state change.</param>
public sealed record DeFiOrderResult(
    string ClientOrderId,
    string? VenueOrderId,
    DeFiOrderState State,
    decimal FilledQuantity,
    decimal? AveragePrice,
    string Venue,
    string Symbol,
    DeFiOrderSide Side,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

// ── Positions ─────────────────────────────────────────────────────────────────

/// <summary>Current open position for a single symbol on a venue.</summary>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Long or Short expressed as Buy/Sell.</param>
/// <param name="Quantity">Size of the open position in base asset.</param>
/// <param name="AverageEntryPrice">Volume-weighted average entry price.</param>
/// <param name="UnrealisedPnl">Mark-to-market PnL in quote currency.</param>
/// <param name="Venue">Venue identifier.</param>
/// <param name="Timestamp">UTC timestamp of this snapshot.</param>
public sealed record DeFiPositionSnapshot(
    string Symbol,
    DeFiOrderSide Side,
    decimal Quantity,
    decimal AverageEntryPrice,
    decimal UnrealisedPnl,
    string Venue,
    DateTimeOffset Timestamp);

// ── On-chain transactions ─────────────────────────────────────────────────────

/// <summary>
/// Request to broadcast an on-chain transaction.
/// All addresses are loaded by name from the PostgreSQL <c>blockchain_addresses</c> table.
/// </summary>
/// <param name="AddressName">Named address key used to look up the target contract address.</param>
/// <param name="EncodedCalldata">ABI-encoded function calldata (hex, without 0x prefix).</param>
/// <param name="ValueWei">Ether value in wei to attach (0 for non-payable calls).</param>
/// <param name="GasLimit">Gas limit for the transaction; 0 means estimate automatically.</param>
/// <param name="RequestingModuleId">Module ID of the caller.</param>
public sealed record OnChainTransactionRequest(
    string AddressName,
    string EncodedCalldata,
    decimal ValueWei,
    ulong GasLimit,
    string RequestingModuleId);

/// <summary>Result of an on-chain transaction broadcast.</summary>
/// <param name="TxHash">Transaction hash on the target chain; <see langword="null"/> on failure.</param>
/// <param name="Status">Current transaction lifecycle status.</param>
/// <param name="GasUsed">Actual gas consumed; 0 when not yet confirmed.</param>
/// <param name="BlockNumber">Block in which the transaction was included; 0 when pending.</param>
/// <param name="SubmittedAt">UTC timestamp when the transaction was broadcast.</param>
public sealed record OnChainTransactionResult(
    string? TxHash,
    OnChainTxStatus Status,
    ulong GasUsed,
    ulong BlockNumber,
    DateTimeOffset SubmittedAt);

// ── Wallet ────────────────────────────────────────────────────────────────────

/// <summary>
/// Result of a wallet signing operation.
/// </summary>
/// <param name="SignedTxHex">RLP-encoded signed transaction as a hex string.</param>
/// <param name="Address">Signer's wallet address.</param>
public sealed record WalletSignResult(
    string SignedTxHex,
    string Address);

// ── Strategy ──────────────────────────────────────────────────────────────────

/// <summary>A DeFi strategy selection request.</summary>
/// <param name="Symbol">Normalised trading symbol.</param>
/// <param name="Side">Desired trade direction.</param>
/// <param name="Quantity">Target position size in base asset.</param>
/// <param name="MaxSlippageBps">Maximum acceptable slippage in basis points.</param>
/// <param name="RequestingModuleId">Module ID of the caller.</param>
public sealed record DeFiStrategyRequest(
    string Symbol,
    DeFiOrderSide Side,
    decimal Quantity,
    int MaxSlippageBps,
    string RequestingModuleId);

/// <summary>Outcome of strategy engine evaluation or execution.</summary>
/// <param name="StrategyType">Selected strategy.</param>
/// <param name="Venue">Selected execution venue.</param>
/// <param name="EstimatedOutputQuantity">Expected output quantity after fees and slippage.</param>
/// <param name="EstimatedFeesBps">Total estimated fees in basis points.</param>
/// <param name="ExecutionOrder">Order to submit; <see langword="null"/> when strategy is informational only.</param>
/// <param name="ExecutedOrderResult">
/// Populated after <c>ExecuteAsync</c> completes; contains the venue order ID, state, and fill
/// price returned by the fallback chain. <see langword="null"/> for dry-run evaluations.
/// </param>
public sealed record DeFiStrategyResult(
    DeFiStrategyType StrategyType,
    string Venue,
    decimal EstimatedOutputQuantity,
    int EstimatedFeesBps,
    DeFiOrderRequest? ExecutionOrder,
    DeFiOrderResult? ExecutedOrderResult = null);

// ── Fill notifications ────────────────────────────────────────────────────────

/// <summary>A fill event for an open DeFi order.</summary>
/// <param name="ClientOrderId">Caller-generated idempotency key.</param>
/// <param name="VenueOrderId">Exchange-assigned order ID.</param>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Side">Buy or Sell.</param>
/// <param name="FillQuantity">Quantity filled in this event.</param>
/// <param name="FillPrice">Price at which the fill occurred.</param>
/// <param name="TotalFilledQuantity">Cumulative filled quantity including this fill.</param>
/// <param name="RemainingQuantity">Unfilled quantity remaining; -1 when unknown.</param>
/// <param name="Venue">Venue identifier.</param>
/// <param name="FilledAt">UTC timestamp of the fill.</param>
public sealed record DeFiFillNotification(
    string ClientOrderId,
    string VenueOrderId,
    string Symbol,
    DeFiOrderSide Side,
    decimal FillQuantity,
    decimal FillPrice,
    decimal TotalFilledQuantity,
    decimal RemainingQuantity,
    string Venue,
    DateTimeOffset FilledAt);

/// <summary>Real-time order book depth update.</summary>
/// <param name="Symbol">Normalised symbol.</param>
/// <param name="Bids">Best bid levels as (price, size) pairs.</param>
/// <param name="Asks">Best ask levels as (price, size) pairs.</param>
/// <param name="Timestamp">Exchange timestamp.</param>
public sealed record DeFiOrderBookUpdate(
    string Symbol,
    IReadOnlyList<(decimal Price, decimal Size)> Bids,
    IReadOnlyList<(decimal Price, decimal Size)> Asks,
    DateTimeOffset Timestamp);

// ── Enumerations ──────────────────────────────────────────────────────────────

/// <summary>Order side enumeration.</summary>
public enum DeFiOrderSide
{
    /// <summary>Buy (long) side.</summary>
    Buy,
    /// <summary>Sell (short) side.</summary>
    Sell,
}

/// <summary>Order type enumeration.</summary>
public enum DeFiOrderType
{
    /// <summary>Execute immediately at best available price.</summary>
    Market,
    /// <summary>Execute at the specified limit price or better.</summary>
    Limit,
    /// <summary>Trigger a market order when the stop price is reached.</summary>
    StopMarket,
    /// <summary>Trigger a limit order when the stop price is reached.</summary>
    StopLimit,
}

/// <summary>Order lifecycle state enumeration.</summary>
public enum DeFiOrderState
{
    /// <summary>Order submitted but not yet acknowledged by the venue.</summary>
    Pending,
    /// <summary>Order accepted and resting in the order book.</summary>
    Open,
    /// <summary>Order has been partially executed; remainder resting.</summary>
    PartiallyFilled,
    /// <summary>Order fully executed.</summary>
    Filled,
    /// <summary>Order cancelled by the requester or the venue.</summary>
    Cancelled,
    /// <summary>Order rejected by the venue.</summary>
    Rejected,
}

/// <summary>On-chain transaction lifecycle status.</summary>
public enum OnChainTxStatus
{
    /// <summary>Transaction has been broadcast to the mempool.</summary>
    Pending,
    /// <summary>Transaction is included in a block and confirmed.</summary>
    Confirmed,
    /// <summary>Transaction was reverted by the EVM.</summary>
    Reverted,
    /// <summary>Broadcast failed — transaction was never accepted by a node.</summary>
    Failed,
}

/// <summary>DeFi strategy type enumeration.</summary>
public enum DeFiStrategyType
{
    /// <summary>Direct perpetual trade on HYPERLIQUID.</summary>
    HyperliquidPerpetual,
    /// <summary>Spot swap via Camelot DEX on Arbitrum.</summary>
    CamelotSpotSwap,
    /// <summary>Spot swap via DFYN DEX.</summary>
    DfynSpotSwap,
    /// <summary>Liquidity provisioning or collateral swap via Balancer.</summary>
    BalancerPool,
    /// <summary>Supply, borrow, or repay via Morpho protocol.</summary>
    MorphoLending,
    /// <summary>Multi-hop path through nHOP router.</summary>
    NHopRoute,
}
